# Linux Kernel Anti-Pattern Detector Configuration

# Analysis Settings
analysis:
  kernel_repository: "https://github.com/torvalds/linux.git"
  clone_depth: 1  # Shallow clone for faster download
  max_file_size: 10485760  # 10MB max file size to analyze
  exclude_patterns:
    - "*.o"
    - "*.ko"
    - "*.a"
    - "*.so"
    - "*.d"
    - "*.mod.c"
    - "*.cmd"
    - "*.tmp"
    - "*.orig"
    - "*.rej"
    - "*.patch"

# Anti-Pattern Detection Rules
detection_rules:
  memory_management:
    enabled: true
    severity: "high"
    patterns:
      - "kmalloc.*without.*kfree"
      - "kfree.*without.*kmalloc"
      - "use.*after.*free"
      - "double.*free"
      - "null.*pointer.*dereference"
      - "memory.*leak"
    directories: ["drivers", "kernel", "mm", "fs"]
    
  concurrency:
    enabled: true
    severity: "high"
    patterns:
      - "race.*condition"
      - "deadlock"
      - "missing.*lock"
      - "double.*lock"
      - "lock.*ordering.*violation"
      - "spinlock.*without.*unlock"
    directories: ["kernel", "drivers", "fs", "net"]
    
  error_handling:
    enabled: true
    severity: "medium"
    patterns:
      - "unchecked.*return.*value"
      - "missing.*error.*handling"
      - "ignored.*error.*code"
      - "wrong.*error.*propagation"
      - "error.*code.*not.*checked"
    directories: ["drivers", "fs", "net", "kernel"]
    
  security:
    enabled: true
    severity: "critical"
    patterns:
      - "buffer.*overflow"
      - "format.*string.*vulnerability"
      - "privilege.*escalation"
      - "information.*disclosure"
      - "stack.*overflow"
      - "heap.*overflow"
    directories: ["security", "drivers", "fs", "net"]
    
  performance:
    enabled: true
    severity: "medium"
    patterns:
      - "O\\(n\\^2\\).*algorithm"
      - "unnecessary.*memory.*allocation"
      - "inefficient.*data.*structure"
      - "cache.*miss.*pattern"
      - "excessive.*copying"
    directories: ["kernel", "drivers", "fs", "mm"]
    
  code_quality:
    enabled: true
    severity: "low"
    patterns:
      - "magic.*numbers"
      - "hardcoded.*values"
      - "complex.*functions"
      - "code.*duplication"
      - "long.*functions"
    directories: ["drivers", "fs", "net", "kernel"]
    
  api_usage:
    enabled: true
    severity: "medium"
    patterns:
      - "deprecated.*function"
      - "wrong.*API.*usage"
      - "missing.*parameter.*validation"
      - "incorrect.*flags"
      - "wrong.*function.*call"
    directories: ["drivers", "fs", "net", "kernel"]

# Output Settings
output:
  report_format: "json"  # json, html, text
  include_source: true
  include_line_numbers: true
  include_context: 3  # Number of lines before/after match
  severity_colors:
    critical: "red"
    high: "yellow"
    medium: "blue"
    low: "green"

# Performance Settings
performance:
  max_concurrent_analyzers: 4
  chunk_size: 1000  # Lines per chunk for processing
  timeout_seconds: 300  # Timeout for individual file analysis
  memory_limit_mb: 1024  # Memory limit for analysis

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "kernel_analysis.log"
  console_output: true
  include_timestamps: true 